name: Deploy Site
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read

defaults:
  run:
    shell: bash
jobs:
  deploy:
    name: Deploy tp FTP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Install PNPM
        run: npm install --location=global pnpm

      - name: Install Dependency
        run: pnpm install --no-frozen-lockfile

      - name: Build all packages
        run: pnpm build:packages"

      - name: Build components.sveltin.io site
        run: pnpm build:sites"
        env:
          VITE_PUBLIC_BASE_PATH: https://components.sveltin.io

      - name: FTP Deploy to production domain
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.PROD_FTP_HOSTNAME }}
          username: ${{ secrets.PROD_FTP_USERNAME }}
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          dry-run: false
          local-dir: ./build/
          server-dir: ${{ secrets.PROD_FTP_SERVER_FOLDER }}
          exclude: .git*
            - .git*/**
            -  **/.git*/**
            - node_modules/**
            - node_modules/**/*
